### ISSUE TITLE
Anxiety

### ISSUE THREAD

**Issue by alexozer** [wizard97/iSkipper#1]
I have an issue containing my excitement over this. Please help.

**Comment by orangeturtle739** [comment]
We'll release a full write up soon, which I think should help.

**Comment by alexozer** [comment]
@orangeturtle739 Thanks, that's reassuring.

**Comment by wizard97** [comment]
@alexozer  any interest in helping? Particularly for nefarious scenerios?

**Comment by alexozer** [comment]
@wizard97 I'm very interested in helping. What kind of stuff could be worked on (and nefarious scenarios like)?

**Comment by wizard97** [comment]
Awesome, looking at your GitHub looks like you know your stuff. 

After lots and lots of logic analyzing, looking at hex disassembly, and messing around, we reversed engineered the id generation, PSK modulation and frequency settings, and packet (answer submission) encoding, so we can submit answers and capture other peoples answers and ids using an off the shelf 915mhz transceiver (RFM69). This is already enough to do a ton of cool (and nefarious) things, such as submit several hundred answers per second in lecture under random ids.

The one thing we haven figured out, is the 7 byte ack sent back from the base station after you submit an answer. As of 15 minutes ago, our device can now capture these responses, we just have no idea what the 7 bytes represent. Once this is figured, we would have basically reverse engineered the entire device.

In terms of nefarious use cases, we have potential pranks that we have considered, but were keeping that on the DL for now...

**Comment by alexozer** [comment]
That's incredibly impressive. I've used an rfm69 before, although using
just a library. Would we need a base station to try to figure out the ack
packet?

**Comment by wizard97** [comment]
Yeah, thats correct, we have found several base stations scattered across lecture halls that we quickly test out our device on late at night.  Here is some response data captured from the base station: https://github.com/wizard97/iSkipper/tree/master/data/base_response

The 7 byte payload is not the same, even with the same id and answer. Right now we think it is some hashed timestamp with some other stuff mixed in.

**Comment by wizard97** [comment]
Also, we wish to make a full clone of the iClicker (a device that behaves exactly like a real one). If you are comfortable with basic Arduino development, this might be an interesting project. Shouldn't be too hard, as all you have to do is make calls to our [emulator class](https://github.com/wizard97/iSkipper/blob/master/emulator/iSkipper/iClickerEmulator.h)

**Comment by alexozer** [comment]
I'll definitely capable of doing the Arduino stuff, do we have a separate
radio module to work with? Other things might be interesting too.
