### ISSUE TITLE
Sending iSkipper-Only Answers

### ISSUE THREAD

**Issue by charlescao460** [wizard97/iSkipper#9]
Hi, I found some strange behaviors of the newest iSkipper Arduino library.

`emulator\iSkipper\examples\submit`  sends answers that can only be recognized by the other iSkipper, but not the real base. And the `submitAnswer()` function would only use a weirdly fixed ID no matter what the argument ID is. (In my case, it's 0x40000040)

However, these problem won't show on the old version of the library (e.g. [Commit d5738ae](https://github.com/wizard97/iSkipper/tree/d5738ae58a69b757a74fbf0b442896400329efcb))

I am using Arduino Nano with RFM69HW. This problem also happened on the real Nano, not only on my [iSkipper-In-One-Package](https://github.com/charlescao460/iSkipper-In-One-Package)

**Comment by wizard97** [comment]
Thanks for pointing this out. I tested this on my feather before merging it into master. Looks like there are still some issues though on other platforms. 

I am going to revert this commit and move it back to dev, where I can debug it some more. Could you let me know if this issue exists with https://github.com/wizard97/iSkipper/commit/64ecd6ddb2aeb090f9617a8458f2eabb6944868d?

**Comment by charlescao460** [comment]
Turns out it was the problem of Arduino or something, fixed after I update my Arduino IDE. Sorry about this late reply. 

Looking forward to implement full-functional simulation after you confirm the ACK decoding. We should know how everything works after that.

**Comment by charlescao460** [comment]
Sadly, this problem shows again. I've checked that commit [c9a81d40](https://github.com/wizard97/iSkipper/tree/c9a81d46491679ef925d359c865b17efc4248750) works well but master does not. [Here](https://github.com/wizard97/iSkipper/compare/c9a81d46491679ef925d359c865b17efc4248750...master) is the comparison. I guess it may be the problem in `iClickerEmulator.cpp ` that you deleted `iClickerEmulator::encodeAns` and create a new function ` iClickerEmulator::computeChecksum`. 

I am really sorry about previous late reply.

Could you please check the code to see which part may cause this problem? Again, it always sends answer with ID 0x40000040, this might be a clue for your investigation. 

Thank you!

**Comment by wizard97** [comment]
Hi Charles,

Thank you looking further into it. I think I found the problem... super dumb mistake on my part. I forgot to call `encodeId()` which explains why you always observed that fixed ID. https://github.com/wizard97/iSkipper/commit/3b8604864ffd9d05197d911d0054bcedc9dacce9 should fix it. Since I don't have a base station, I am unable to test it. Could you verify this fix works?

Thanks,
Aaron

**Comment by charlescao460** [comment]
Of course, I'll test it tonight!

**Comment by charlescao460** [comment]
![image](https://user-images.githubusercontent.com/33741854/58737601-3eb50e00-83d0-11e9-9226-ae8afa50a9f5.png)
Looks good. Issue resolved.
Thank you for doing this!
